version: '3.8'
services:
  backend:
    build:
      context: .
      target: backend-runtime
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: frontend-runtime
    ports:
      - "5173:80"
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: gazette_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: