name: CI

on:
  push:
    branches:
      - main
      - staging
      - dev
      - branche-de-france
  pull_request:
    branches:
      - main
      - staging
      - dev
      - branche-de-france

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        run: npm install -g pnpm@10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

  typecheck:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        run: npm install -g pnpm@10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript typecheck
        run: pnpm -r run typecheck

  build:
    needs: typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        run: npm install -g pnpm@10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        env:
          NODE_ENV: production
          CI: true
        run: pnpm -r build

  lighthouse:
    name: Lighthouse Accessibility Audit
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        run: npm install -g pnpm@10.11.0

      - name: Create .env file for CI
        run: |
          cat > .env << EOF
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_PORT=${{ secrets.DB_PORT }}
          BACKEND_PORT=${{ secrets.BACKEND_PORT }}
          NODE_ENV=test
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}
          ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
          FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          EOF
          echo "Created .env file (values hidden for security)"
          echo "Checking if all required secrets are set..."
          if [ -z "${{ secrets.DB_USER }}" ] || [ -z "${{ secrets.BACKEND_PORT }}" ] || [ -z "${{ secrets.FRONTEND_PORT }}" ]; then
            echo "❌ Missing required secrets!"
            exit 1
          fi
          echo "✅ All required secrets are set"

      - name: Run Lighthouse CI
        env:
          FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
        run: |
          echo "Getting Docker host IP..."
          DOCKER_HOST_IP=$(docker network inspect bridge | jq -r '.[0].IPAM.Config[0].Gateway')
          echo "Docker host IP: $DOCKER_HOST_IP"

          echo "=== Network Diagnostics ==="
          echo "Docker network list:"
          docker network ls
          echo "Docker network inspect:"
          docker network inspect gazette_gazette-network || echo "Network not found"

          echo "=== Container Status ==="
          docker compose ps

          echo "=== Port Mappings ==="
          docker compose port frontend ${{ secrets.FRONTEND_PORT }} || echo "Frontend port mapping failed"
          docker compose port backend 3000 || echo "Backend port mapping failed"

          echo "=== Connectivity Tests ==="
          echo "Testing localhost connectivity..."
          curl -v http://localhost:${{ secrets.FRONTEND_PORT }}/ || echo "localhost:Frontend not accessible"
          curl -v http://localhost:3000/ || echo "localhost:Backend not accessible"

          echo "Testing Docker host IP connectivity..."
          curl -v http://$DOCKER_HOST_IP:${{ secrets.FRONTEND_PORT }}/ || echo "Docker IP:Frontend not accessible"
          curl -v http://$DOCKER_HOST_IP:3000/ || echo "Docker IP:Backend not accessible"

          echo "=== Container IPs ==="
          FRONTEND_IP=$(docker inspect gazette-frontend-1 | jq -r '.[0].NetworkSettings.Networks.gazette_gazette-network.IPAddress')
          echo "Frontend container IP: $FRONTEND_IP"

          echo "=== Final Test ==="
          if [ -n "$FRONTEND_IP" ]; then
            echo "Testing direct container IP..."
            curl -v http://$FRONTEND_IP:${{ secrets.FRONTEND_PORT }}/ || echo "Container IP:Frontend not accessible"
          fi

          echo "Installing Lighthouse CLI..."
          npm install -g @lhci/cli@0.15.x

          echo "Running Lighthouse with localhost..."
          lhci collect --url=http://localhost:${{ secrets.FRONTEND_PORT }}/
          lhci upload --target=temporary-public-storage
