name: CI

on:
  push:
    branches:
      - main
      - staging
      - dev
      - branche-de-france
  pull_request:
    branches:
      - main
      - staging
      - dev
      - branche-de-france

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        run: npm install -g pnpm@10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

  typecheck:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        run: npm install -g pnpm@10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript typecheck
        run: pnpm -r run typecheck

  build:
    needs: typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        run: npm install -g pnpm@10.11.0

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        env:
          NODE_ENV: production
          CI: true
        run: pnpm -r build

  lighthouse:
    name: Lighthouse Accessibility Audit
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Setup pnpm
        run: npm install -g pnpm@10.11.0

      - name: Create .env file for CI
        run: |
          cat > .env << EOF
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          DB_PORT=${{ secrets.DB_PORT }}
          BACKEND_PORT=${{ secrets.BACKEND_PORT }}
          NODE_ENV=test
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}
          ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }}
          FRONTEND_PORT=${{ secrets.FRONTEND_PORT }}
          NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          EOF

      - name: Start Docker services
        run: |
          echo "Starting all services with docker compose..."
          docker compose up --build -d
          echo "Waiting for containers to be ready..."
          sleep 15
          echo "Checking services status..."
          docker compose ps
          echo "Checking if backend is accessible..."
          curl -f http://localhost:3000/ || echo "Backend not accessible"
          echo "Checking if frontend is accessible..."
          curl -f http://localhost:3002/ || echo "Frontend not accessible"
          echo "Installing missing binaries..."
          docker compose exec backend pnpm install || echo "Backend container not ready"
          docker compose exec frontend pnpm install || echo "Frontend container not ready"

      - name: Run Lighthouse authentication script
        run: |
          echo "Running Lighthouse script in Docker container..."
          docker run --rm \
            --network gazette_gazette-network \
            -v $(pwd)/.github/scripts:/scripts \
            -v $(pwd):/workspace \
            -w /scripts \
            node:20-alpine \
            sh -c "
              npm install -g pnpm@10.12.4
              echo '{\"type\": \"module\"}' > package.json
              pnpm add lighthouse puppeteer wait-on
              npx puppeteer browsers install chrome
              HOST_IP=\$(ip route | grep default | awk '{print \$3}')
              echo \"Using host IP: \$HOST_IP\"
              BACKEND_URL=http://\$HOST_IP:3000 FRONTEND_URL=http://\$HOST_IP:3002 node lighthouse-auth.js
            "

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: ./lighthouse-report-*.html
